#!/bin/sh
# Resources Sets for RNAseq Analysis
# Usage: RNAseqPipeline <1:Resource_set>
# also called 'species'
	
# OUTPUT: directories/files for RNAseq Pipeline
# 
	set -e
	set -o pipefail

# Read Input
	species=$1

# Resources Summary
# For each reference genome set the following supporting data are required

	# res : Folder containing exon, exon-boundary, intron information.
		# Reference annotation to be used
		# generated by ????? script

	# chrs : Fasta index file containing chromosome sizes

	# chrfile : Translates UCSC chromosome name to simple name
		# 2 columns; <1: Name> <2:UCSC_name>
			# 13	 chr13
			# X	chrX

	# bwtindex : Folder containing index Files for Bowtie Index
		# [Note implemented]

	# TEdata : Repeat Masker table (RMDB) from UCSC
		# Processed to 7 columns
		# only LINE/SINE/LTR/DNA
		# <chr_name> <start> <end> <strand> <repName> <repClass> <repFamily>

	# chimeric : Repeat Masker table from UCSC; looks same as above


if [ "$species" == "hg19gc_v14" ]; then
# Human Genome 19r GENCODE v14 [MODIFIED]
        res=/home/ababaian/resources/sets/hg19gc_v14/
        chrs=/home/ababaian/resources/chimeric/hg19r.chr.size
        chrfile=/home/ababaian/resources/chimeric/hg19r.bwa.names
        btwindex=/home/ababaian/resources/hg19/bowtie/
	TEdata=/home/ababaian/resources/sets/RM/SINES_LINES_LTRS_hg19
	chimeric=/home/ababaian/resources/sets/RM/ForChimericSearch_hg19

elif [ "$species" == "assembly" ]; then
        res='/home/ababaian/resources/sets/assembly/hl_120913/$name'
        chrs=/home/ababaian/resources/chimeric/hg19r.chr.size
        chrfile=/home/ababaian/resources/chimeric/hg19r.bwa.names
	btwindex=/home/ababaian/resources/hg19/bowtie/
	TEdata=/home/ababaian/resources/sets/RM/SINES_LINES_LTRS_hg19
	chimeric=/home/ababaian/resources/sets/RM/ForChimericSearch_hg19

elif [ "$species" == "HS0988r" ]; then
        res=/home/ababaian/resources/sets/HS0988r/
        chrs=/home/ababaian/resources/chimeric/hg19r.chr.size
        chrfile=/home/ababaian/resources/chimeric/hg19r.bwa.names
	btwindex=/home/ababaian/resources/hg19/bowtie/
	TEdata=/home/ababaian/resources/sets/RM/SINES_LINES_LTRS_hg19
	chimeric=/home/ababaian/resources/sets/RM/ForChimericSearch_hg19

elif [ "$species" == "hg19r" ]; then
# Human Genome 19r GENCODE v14 [Not working, needs it's own reference assembly
        res=/projects/mbilenky/resources/hg19gc_v14/
        chrs=/home/ababaian/resources/chimeric/hg19r.chr.size
        chrfile=/home/ababaian/resources/chimeric/hg19r.bwa.names
	bwtindex=/projects/mbilenky/resources/bowtie_hg19/
        TEdata=/projects/mbilenky/resources/RepeatMasker/SINES_LINES_LTRS_hg19
        chimeric=/projects/mbilenky/resources/RepeatMasker/ForChimericSearch_hg19

elif [ "$species" == "mm9v65" ]; then
	res=/projects/03/genereg/projects/SOLEXA/resources/Ensembl_v65/mm9v65/
	chrs=/projects/03/genereg/projects/SOLEXA/chr_info/mm9.chrom.sizes
	chrfile=/projects/03/genereg/projects/SOLEXA/resources/UCSC_chr/mm9.bwa2ucsc.names
	bwtindex=/projects/mbilenky/resources/bowtie_mm9/
	TEdata=/projects/mbilenky/mlc/RepeatMasker/RetroTransposons
	chimeric=/projects/mbilenky/resources/RepeatMasker/ForChimericSearch_mm9

elif [ "$species" == "mm9refSeq" ]; then
	res=/projects/03/genereg/projects/SOLEXA/resources/UCSC_mm9/refGene_20120726/
	chrs=/projects/03/genereg/projects/SOLEXA/chr_info/mm9.chrom.sizes
	chrfile=/projects/03/genereg/projects/SOLEXA/resources/UCSC_chr/mm9.bwa2ucsc.names
	bwtindex=/projects/mbilenky/resources/bowtie_mm9/
	TEdata=/projects/mbilenky/mlc/RepeatMasker/RetroTransposons
	chimeric=/projects/mbilenky/resources/RepeatMasker/ForChimericSearch_mm9

elif [ "$species" == "mm9v67" ]; then
 	res=/projects/03/genereg/projects/SOLEXA/resources/Ensembl_v67/mm9v67/
	chrs=/projects/03/genereg/projects/SOLEXA/chr_info/mm9.chrom.sizes
	chrfile=/projects/03/genereg/projects/SOLEXA/resources/UCSC_chr/mm9.bwa2ucsc.names
	bwtindex=/projects/mbilenky/resources/bowtie_mm9/
	TEdata=/projects/mbilenky/mlc/RepeatMasker/RetroTransposons
	chimeric=/projects/mbilenky/resources/RepeatMasker/ForChimericSearch_mm9
	
else
	echo "RNAgetRes.sh ERROR: No matching resources for species: $species" 1>&2
	exit 1
fi

echo $res,$chrs,$chrfile,$TEdata,$chimeric
